databases:
  - name: hello-world-db
    plan: free
    databaseName: helloworld
    user: hellouser

services:
  - type: web
    name: hello-backend
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements.txt
    startCommand: sh -c "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hello-world-db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /health

  - type: web
    name: hello-frontend
    runtime: static
    plan: free
    buildCommand: bash -c "cd frontend && npm install && npm run build"
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
      - key: NODE_VERSION
        value: "20"
      - key: NODE_OPTIONS
        value: "--max_old_space_size=1536"
